# NOTE: use $$ to escape $ in docker compose yaml

# The config below was obtained from: https://nginxproxymanager.com/guide/#quick-setup

services:

  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80 # public http port
      - 81:81 # web dashboard
      - 443:443 # public https port
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_data:/etc/letsencrypt
      - ./custom_config:/data/nginx/custom # see https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations

volumes:
  nginx_proxy_manager_data: